#修改启动端口后，访问链接必须带/demo
server:
  port: 8082
  servlet:
    context-path: /demo
spring:
  dataSource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/greensgcc?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 3000
      pool-name: myDataSourcePool
      connection-init-sql: select 1
mybatis:
  entity-package: com.test.demo.entity
  mapper-locations: classpath:com/test/demo/dao/mapper/*Mapper.xml
